#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

. "./.common/scripts/log.sh"

log "Running `npm run lint-staged` to validate staged files"
npm run lint-staged
log "Running `task spelling` to check for possible spelling errors"
task spelling
success "Successfully validated the commit"
