---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: desktop
  REPOSITORY_TYPE: packer

includes:
  common: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-common.yml
  packer: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-packer.yml
  fix: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-fix.yml
  lint: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-lint.yml
  software: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-{{OS}}.yml
