---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: desktop
  REPOSITORY_TYPE: packer

includes:
  common: ./.common/taskfiles-desktop/Taskfile-common.yml
  packer: ./.common/taskfiles-desktop/Taskfile-packer.yml
  fix: ./.common/taskfiles-desktop/Taskfile-fix.yml
  lint: ./.common/taskfiles-desktop/Taskfile-lint.yml
  software: ./.common/taskfiles-desktop/Taskfile-{{OS}}.yml
