---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: server
  REPOSITORY_TYPE: packer

includes:
  common: ./.common/taskfiles-server/Taskfile-common.yml
  packer: ./.common/taskfiles-server/Taskfile-packer.yml
  fix: ./.common/taskfiles-server/Taskfile-fix.yml
  lint: ./.common/taskfiles-server/Taskfile-lint.yml
  software: ./.common/taskfiles-server/Taskfile-{{OS}}.yml
